name: Hexo Deploy GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: ColoeusEdward/hexo-deploy-github-pages-action@master
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}

        # The repository the action should deploy to.
        PUBLISH_REPOSITORY: ColoeusEdward/kaf_blog

        # The branch the action should deploy to.
        BRANCH: master