name: 'Hexo Deploy GitHub Pages Action'
description: 'This GitHub action for building and deploying a Hexo project to GitHub pages.'
author: 'Keep Theme Team'
on:
  push:
    branches:
      - master
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'git-commit'
  color: 'blue'
